### ISSUE TITLE
Timeouts when using :weekly intervals greater than 2

### ISSUE THREAD

**Issue by emarchak** [Omerlo-Technologies/ex_cycle#26]
Sorry to bother again! 

We upgraded to 0.6.0 (thank you!) and now are getting timeouts when using :weekly  with intervals greater than 2. The following test fails, but if I change the interval with 2 it's able to complete. Adding `week_starting_on: :default` or another day doesn't appear to change anything.

Let me know how we can help! I really appreciate how speedy you've been with the releases.

Repro:
```elixir
 test "weekly with interval of 3 returns occurrences" do
      occurrences =
        ExCycle.new()
        |> ExCycle.add_rule(:weekly,
          interval: 3,
          days: [:monday],
          starts_at: ~D[2024-10-03],
          timezone: "America/New_York",
          hours: [9],
          minutes: [0]
        )
        |> ExCycle.occurrences(~D[2024-10-03])
        |> Enum.take(3)

      assert occurrences == [
               DateTime.new!(~D[2024-10-04], ~T[09:00:00], "America/New_York"),
               DateTime.new!(~D[2024-09-30], ~T[09:00:00], "America/New_York"),
               DateTime.new!(~D[2024-10-02], ~T[09:00:00], "America/New_York")
             ]
    end
```
    
```bash
  1) test weekly with interval of 3 returns occurrences 
     ** (ExUnit.TimeoutError) test timed out after 60000ms. You can change the timeout:

       1. per test by setting "@tag timeout: x" (accepts :infinity)
       2. per test module by setting "@moduletag timeout: x" (accepts :infinity)
       3. globally via "ExUnit.start(timeout: x)" configuration
       4. by running "mix test --timeout x" which sets timeout
       5. or by running "mix test --trace" which sets timeout to infinity
          (useful when using IEx.pry/0)

     where "x" is the timeout given as integer in milliseconds (defaults to 60_000).
     
     code: |> ExCycle.occurrences(~D[2024-10-03])
     stacktrace:
       (elixir 1.17.1) lib/calendar/iso.ex:1941: Calendar.ISO.days_in_previous_years/1
       (elixir 1.17.1) lib/calendar/iso.ex:1927: Calendar.ISO.days_to_year/3
       (elixir 1.17.1) lib/calendar/iso.ex:1917: Calendar.ISO.days_to_year/1
       (elixir 1.17.1) lib/calendar/iso.ex:887: Calendar.ISO.date_from_iso_days/1
       (elixir 1.17.1) lib/calendar/iso.ex:797: Calendar.ISO.naive_datetime_from_iso_days/1
       (elixir 1.17.1) lib/calendar/naive_datetime.ex:1410: NaiveDateTime.from_iso_days/3
       (elixir 1.17.1) lib/map.ex:916: Map.update!/3
       (ex_cycle 0.6.0) lib/ex_cycle/rule.ex:186: ExCycle.Rule.do_next/2
       (elixir 1.17.1) lib/map.ex:916: Map.update!/3
       (ex_cycle 0.6.0) lib/ex_cycle/rule.ex:121: ExCycle.Rule.init/3
       (elixir 1.17.1) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
       (elixir 1.17.1) lib/map.ex:916: Map.update!/3
       (ex_cycle 0.6.0) lib/ex_cycle.ex:90: ExCycle.occurrences/3
```

**Comment by Matsa59** [comment]
Ahhhhh I get it ... sorry the weekly system were entirely wrong ...

Do you validate this test

```elixir
    test "weekly with interval of 3 returns occurrences" do
      occurrences =
        ExCycle.new()
        |> ExCycle.add_rule(:weekly,
          interval: 3,
          days: [:monday],
          starts_at: ~D[2024-10-03],
          timezone: "America/New_York",
          hours: [9],
          minutes: [0]
        )
        |> ExCycle.occurrences(~D[2024-10-03])
        |> Enum.take(3)

      assert occurrences == [
               DateTime.new!(~D[2024-10-21], ~T[09:00:00], "America/New_York"),
               DateTime.new!(~D[2024-11-11], ~T[09:00:00], "America/New_York"),
               DateTime.new!(~D[2024-12-02], ~T[09:00:00], "America/New_York")
             ]
    end
```

**Comment by Matsa59** [comment]
And you don't brother us at all. Thanks a lot for your time

**Comment by emarchak** [comment]
Thanks again! I can confirm that the longer intervals are working on 0.6.1!
